[general]
format=wav49|gsm|wav
serveremail=asterisk@example.com
attach=yes
maxmsg=100
maxsecs=180
minsecs=3
maxgreet=60

[default]
1000 => 1234,Agent 1000,agent1000@example.com
1001 => 1234,Agent 1001,agent1001@example.com
