[global]

[cdr]
connection=asterisk
table=cdrs
; Use alias format for adaptive ODBC
alias tenant_id => ${CDR(accountcode)}
alias call_date => ${STRFTIME(${CDR(start)},,%Y-%m-%d %H:%M:%S)}
alias caller_id => ${CDR(clid)}
alias destination => ${CDR(dst)}
alias channel => ${CDR(channel)}
alias destination_channel => ${CDR(dstchannel)}
alias duration => ${CDR(duration)}
alias billable_duration => ${CDR(billsec)}
alias disposition => ${CDR(disposition)}
alias unique_id => ${CDR(uniqueid)}
alias recording_url => ${CDR(recordingfile)}
alias user_field => ${CDR(userfield)}
