[settings]
ps_endpoints => odbc,asterisk,ps_endpoints
ps_auths => odbc,asterisk,ps_auths
ps_aors => odbc,asterisk,ps_aors
ps_endpoint_id_ips => odbc,asterisk,ps_endpoint_id_ips
ps_acl => odbc,asterisk,ps_acl
ps_endpoint_acl => odbc,asterisk,ps_endpoint_acl
queues => odbc,asterisk,queues
queue_members => odbc,asterisk,queue_members
ps_transports => odbc,asterisk,ps_transports
