-- Create conversations table
CREATE TABLE IF NOT EXISTS `conversations` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `tenant_id` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `customer_id` bigint DEFAULT NULL,
  `customer_name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `customer_phone` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `customer_email` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `channel` enum('web','whatsapp','facebook','instagram','twitter','sms','telegram') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'web',
  `external_id` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `status` enum('queued','bot','agent','closed','resolved') COLLATE utf8mb4_unicode_ci DEFAULT 'bot',
  `assigned_agent_id` bigint DEFAULT NULL,
  `assigned_queue_id` bigint DEFAULT NULL,
  `language` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT 'en',
  `bot_confidence` float DEFAULT '1',
  `bot_message_count` int DEFAULT '0',
  `handoff_reason` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `handoff_triggered_by` enum('bot','customer','rule','timeout','agent') COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `priority` enum('low','medium','high','urgent') COLLATE utf8mb4_unicode_ci DEFAULT 'medium',
  `tags` json DEFAULT NULL,
  `customer_context` json DEFAULT NULL,
  `started_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `assigned_at` timestamp NULL DEFAULT NULL,
  `closed_at` timestamp NULL DEFAULT NULL,
  `first_response_at` timestamp NULL DEFAULT NULL,
  `last_message_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `resolution_time` int DEFAULT NULL,
  `customer_rating` tinyint DEFAULT NULL,
  `customer_feedback` text COLLATE utf8mb4_unicode_ci,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_tenant_status` (`tenant_id`,`status`),
  KEY `idx_agent` (`assigned_agent_id`),
  KEY `idx_channel` (`channel`,`status`),
  KEY `idx_external_id` (`channel`,`external_id`),
  KEY `idx_customer` (`customer_id`),
  KEY `idx_last_message` (`last_message_at`),
  KEY `assigned_queue_id` (`assigned_queue_id`),
  CONSTRAINT `conversations_ibfk_1` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`id`) ON DELETE CASCADE,
  CONSTRAINT `conversations_ibfk_2` FOREIGN KEY (`customer_id`) REFERENCES `contacts` (`id`) ON DELETE SET NULL,
  CONSTRAINT `conversations_ibfk_3` FOREIGN KEY (`assigned_agent_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `conversations_ibfk_4` FOREIGN KEY (`assigned_queue_id`) REFERENCES `queues` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
