-- Create ai_agent_config table
CREATE TABLE IF NOT EXISTS `ai_agent_config` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `tenant_id` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `is_enabled` tinyint(1) DEFAULT '1',
  `model` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT 'gemini-pro',
  `api_key_encrypted` text COLLATE utf8mb4_unicode_ci,
  `system_prompt` text COLLATE utf8mb4_unicode_ci,
  `personality` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT 'professional',
  `max_tokens` int DEFAULT '500',
  `temperature` float DEFAULT '0.7',
  `auto_handoff_enabled` tinyint(1) DEFAULT '1',
  `handoff_confidence_threshold` float DEFAULT '0.5',
  `handoff_message_count` int DEFAULT '10',
  `handoff_timeout_seconds` int DEFAULT '300',
  `response_delay_ms` int DEFAULT '1000',
  `collect_email` tinyint(1) DEFAULT '1',
  `collect_phone` tinyint(1) DEFAULT '1',
  `collect_name` tinyint(1) DEFAULT '1',
  `business_hours_only` tinyint(1) DEFAULT '0',
  `fallback_message` text COLLATE utf8mb4_unicode_ci,
  `greeting_message` text COLLATE utf8mb4_unicode_ci,
  `rag_enabled` tinyint(1) DEFAULT '1',
  `rag_similarity_threshold` float DEFAULT '0.7',
  `rag_max_results` int DEFAULT '3',
  `sentiment_analysis_enabled` tinyint(1) DEFAULT '1',
  `intent_detection_enabled` tinyint(1) DEFAULT '1',
  `language_detection_enabled` tinyint(1) DEFAULT '0',
  `supported_languages` json DEFAULT NULL,
  `analytics_enabled` tinyint(1) DEFAULT '1',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `profile_name` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'Default Profile',
  `description` text COLLATE utf8mb4_unicode_ci,
  `website_id` bigint DEFAULT NULL,
  `is_default` tinyint(1) DEFAULT '0',
  `kb_tags` json DEFAULT NULL COMMENT 'KB articles matching these tags',
  PRIMARY KEY (`id`),
  KEY `fk_ai_agent_website` (`website_id`),
  KEY `idx_tenant_id` (`tenant_id`),
  CONSTRAINT `ai_agent_config_ibfk_1` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_ai_agent_website` FOREIGN KEY (`website_id`) REFERENCES `websites` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
