-- 01 - Create Asterisk Realtime Tables
-- This creates the PJSIP realtime tables that Asterisk needs

USE callcenter;

-- ============================================================================
-- PJSIP REALTIME TABLES (Asterisk 20+)
-- ============================================================================

CREATE TABLE IF NOT EXISTS ps_endpoints (
  id VARCHAR(128) PRIMARY KEY,
  transport VARCHAR(128),
  aors VARCHAR(256),
  auth VARCHAR(128),
  context VARCHAR(128),
  disallow VARCHAR(256),
  allow VARCHAR(256),
  direct_media VARCHAR(10),
  connected_line_method VARCHAR(20),
  direct_media_method VARCHAR(20),
  direct_media_glare_mitigation VARCHAR(20),
  disable_direct_media_on_nat VARCHAR(10),
  dtmf_mode VARCHAR(20),
  external_media_address VARCHAR(128),
  force_rport VARCHAR(10),
  ice_support VARCHAR(10),
  identify_by VARCHAR(128),
  mailboxes VARCHAR(256),
  moh_suggest VARCHAR(128),
  outbound_auth VARCHAR(128),
  outbound_proxy VARCHAR(256),
  rewrite_contact VARCHAR(10),
  rtp_ipv6 VARCHAR(10),
  rtp_symmetric VARCHAR(10),
  send_diversion VARCHAR(10),
  send_pai VARCHAR(10),
  send_rpid VARCHAR(10),
  timers_min_se INT,
  timers VARCHAR(20),
  timers_sess_expires INT,
  callerid VARCHAR(128),
  callerid_privacy VARCHAR(20),
  callerid_tag VARCHAR(128),
  100rel VARCHAR(10),
  aggregate_mwi VARCHAR(10),
  trust_id_inbound VARCHAR(10),
  trust_id_outbound VARCHAR(10),
  use_ptime VARCHAR(10),
  use_avpf VARCHAR(10),
  media_encryption VARCHAR(20),
  inband_progress VARCHAR(10),
  call_group VARCHAR(128),
  pickup_group VARCHAR(128),
  named_call_group VARCHAR(128),
  named_pickup_group VARCHAR(128),
  device_state_busy_at INT,
  fax_detect VARCHAR(10),
  t38_udptl VARCHAR(10),
  t38_udptl_ec VARCHAR(20),
  t38_udptl_maxdatagram INT,
  t38_udptl_nat VARCHAR(10),
  t38_udptl_ipv6 VARCHAR(10),
  tone_zone VARCHAR(128),
  language VARCHAR(128),
  one_touch_recording VARCHAR(10),
  record_on_feature VARCHAR(128),
  record_off_feature VARCHAR(128),
  rtp_engine VARCHAR(128),
  allow_transfer VARCHAR(10),
  allow_subscribe VARCHAR(10),
  sdp_owner VARCHAR(128),
  sdp_session VARCHAR(128),
  tos_audio VARCHAR(10),
  tos_video VARCHAR(10),
  cos_audio INT,
  cos_video INT,
  sub_min_expiry INT,
  from_domain VARCHAR(128),
  from_user VARCHAR(128),
  mwi_from_user VARCHAR(128),
  dtls_verify VARCHAR(10),
  dtls_rekey VARCHAR(10),
  dtls_cert_file VARCHAR(256),
  dtls_private_key VARCHAR(256),
  dtls_cipher VARCHAR(256),
  dtls_ca_file VARCHAR(256),
  dtls_ca_path VARCHAR(256),
  dtls_setup VARCHAR(20),
  srtp_tag_32 VARCHAR(10),
  media_address VARCHAR(128),
  redirect_method VARCHAR(20),
  set_var TEXT,
  cos INT,
  message_context VARCHAR(128),
  accountcode VARCHAR(128),
  preferred_codec_only VARCHAR(10),
  rtp_keepalive INT,
  rtp_timeout INT,
  rtp_timeout_hold INT,
  bind_rtp_to_media_address VARCHAR(10),
  voicemail_extension VARCHAR(128),
  mwi_subscribe_replaces_unsolicited INT,
  deny VARCHAR(256),
  permit VARCHAR(256),
  acl VARCHAR(128),
  contact_deny VARCHAR(256),
  contact_permit VARCHAR(256),
  contact_acl VARCHAR(128),
  subscribe_context VARCHAR(128),
  fax_detect_timeout INT,
  contact_user VARCHAR(128),
  rpid_immediate VARCHAR(10),
  ignore_183_without_sdp VARCHAR(10),
  max_audio_streams INT,
  max_video_streams INT,
  bundle VARCHAR(10),
  webrtc VARCHAR(10),
  dtls_fingerprint VARCHAR(20),
  incoming_call_offer_pref VARCHAR(20),
  outgoing_call_offer_pref VARCHAR(20),
  stir_shaken VARCHAR(10),
  send_history_info VARCHAR(10),
  allow_unauthenticated_options VARCHAR(10)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ps_auths (
  id VARCHAR(128) PRIMARY KEY,
  auth_type VARCHAR(20),
  nonce_lifetime INT,
  md5_cred VARCHAR(256),
  password VARCHAR(256),
  realm VARCHAR(128),
  username VARCHAR(128)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ps_aors (
  id VARCHAR(128) PRIMARY KEY,
  contact VARCHAR(256),
  default_expiration INT,
  mailboxes VARCHAR(256),
  max_contacts INT,
  minimum_expiration INT,
  remove_existing VARCHAR(10),
  qualify_frequency INT,
  authenticate_qualify VARCHAR(10),
  maximum_expiration INT,
  outbound_proxy VARCHAR(256),
  support_path VARCHAR(10),
  qualify_timeout DECIMAL(4,2),
  voicemail_extension VARCHAR(128),
  remove_unavailable VARCHAR(10)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ps_contacts (
  id VARCHAR(255) PRIMARY KEY,
  endpoint VARCHAR(128),
  uri VARCHAR(511),
  expiration_time BIGINT,
  qualify_frequency INT,
  outbound_proxy VARCHAR(256),
  path TEXT,
  user_agent VARCHAR(255),
  qualify_timeout DECIMAL(4,2),
  reg_server VARCHAR(255),
  authenticate_qualify VARCHAR(10),
  via_addr VARCHAR(255),
  via_port INT,
  call_id VARCHAR(255),
  prune_on_boot VARCHAR(10)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS queue_members (
  uniqueid INT AUTO_INCREMENT PRIMARY KEY,
  queue_name VARCHAR(128),
  interface VARCHAR(128),
  membername VARCHAR(128),
  state_interface VARCHAR(128),
  penalty INT,
  paused INT,
  wrapuptime INT,
  INDEX idx_queue (queue_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

SELECT 'Asterisk realtime tables created!' as status;
